# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('home_phone_number', models.CharField(max_length=20)),
                ('cellphone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
